# Generated by Django 5.0.1 on 2024-02-05 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(max_length=255)),
                ('symptoms', models.CharField(max_length=500)),
                ('blood_type', models.CharField(default='NA', max_length=10)),
                ('blood_pressure', models.FloatField(blank=True, default=0.0, null=True)),
                ('diabetic', models.CharField(default='NA', max_length=10)),
                ('sugar_level', models.IntegerField(blank=True, default=0, null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('heart_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ('created_at',),
            },
        ),
    ]
