# Generated by Django 4.0.8 on 2024-02-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
