# Generated by Django 4.2.9 on 2024-03-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_myuser_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuser',
        ),
    ]
